server:
  port: 8888
  application:
    name: config-server
  profiles:
    active: native
---
spring:
  cloud:
    config:
      server:
        native:
          search-locations: file:////G:/projects/config-server/src/main/resources/configs/{profile}
---
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Test-Exercise-Library-records/Config-Server/
          search-paths:
            - "src/main/resources/configs/{profile}"
