springdoc:
  api-docs:
    path: /library-records-api-docs
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop